### PR TITLE
Dock UI

### PR DESCRIPTION
**Pull request by lixelamos**
This is expandeable dock ui and icons  fix 
[https://www.loom.com/share/fbd867d0fbfe4e2888445c878c63792c?sid=b33b7b36-6756-45e9-a122-d34141a4e82a](url)

### CODE REVIEW

**Comment by sajdakabir** [comment]
hey @lixelamos why did you open another pr you already have a pr please close the previous pr

**Comment by lixelamos** [comment]
closed the prev

**Comment by deewakar-k** [comment]
@lixelamos link not working

**Comment by lixelamos** [comment]
*localhost:3000/inbox/ - 26 September 2024* - Watch Video
<https://www.loom.com/share/fbd867d0fbfe4e2888445c878c63792c>
<https://www.loom.com/share/fbd867d0fbfe4e2888445c878c63792c?utm_medium=gif>

**Comment by deewakar-k** [comment]
@lixelamos avoid changes on yaml files

**Review by deewakar-k — CHANGES_REQUESTED** [review]
unnecessary changes on files

**Pull request closed without merging**
