### PR TITLE
inbox page first version

### LINKED ISSUE #45: [SAT-113] [ui] inobx

### LINKED ISSUE #121: [feat] inbox integration

### LINKED ISSUE #178: [ui] fix size of today icon on dock
The today icon on dock shows the current date, but to accommodate one digit date:it's squeezing it's size where it should be same always irrespective of one digit date or two.

ref image:
Screenshot 2024-10-01 at 12 07 14 AM

figma url: https://www.figma.com/design/VH3rrq9pPP3TFcbXzfF7DN/copy-of-march-UI?m=auto&t=x98yJVjyrWoX3IJy-1

### PR DESCRIPTION
**Pull request by joaorceschini**
- starting inbox page
- changed notes api path
- fixed sidebar today icon

### CODE REVIEW

**Comment by immadsahin** [comment]
does this close this: https://github.com/marchhq/march/issues/178? @joaorceschini

**Comment by joaorceschini** [comment]
> does this close this: #178? @joaorceschini

yeah

**Comment by sajdakabir** [comment]
@deewakar-k, I think you should take a look into this PR.

**Comment by deewakar-k** [comment]
> @deewakar-k, I think you should take a look into this PR.

sure

**Review by sajdakabir — APPROVED** [review]

**Pull request merged**
