### PR TITLE
add: expandable doc animation

### PR DESCRIPTION
**Pull request by bhataasim1**
Add dock animation on hover as in this [Dock Menu Svelte](https://animation-svelte.vercel.app/magic/dock)

### CODE REVIEW

**Comment by bhataasim1** [comment]
https://github.com/user-attachments/assets/71416d2e-260f-4836-820b-8cd16ef37566

**Comment by deewakar-k** [comment]
@bhataasim1 performance optimization?

**Comment by bhataasim1** [comment]
@deewakar-k  i think, there isn't any performance issue. however we could limit the mouse movement updates

**Comment by sajdakabir** [comment]
Hey @bhataasim1 , thank you for making the PR to march.

However, I found some issues in your PR:

It's moving the whole page, which it shouldn't.
Any movement in the sidebar should not affect other parts.

https://github.com/user-attachments/assets/4bef32da-f5d3-4877-bcf7-e58bf7baa1e8

**Comment by bhataasim1** [comment]
Thanks @sajdakabir, i just noticed, will fix it.

**Comment by bhataasim1** [comment]
https://github.com/user-attachments/assets/0aeaa499-c04c-4fa2-8a06-68dbedf0feef

@sajdakabir Now the issue is fixed, thanks

**Comment by sajdakabir** [comment]
thank you for making the changes let me check the pr once again

**Comment by sajdakabir** [comment]
hey @bhataasim1 , please  take a pull from the main branch, then it should be good to merge

**Comment by bhataasim1** [comment]
Hey @sajdakabir , Done you can merge it now

**Pull request merged**
