### PR TITLE
issue#135

### LINKED ISSUE #135: [ui] expandable dock
expand dock on hover for more options: toggle, profile, feedback

### PR DESCRIPTION
**Pull request by lixelamos**

### CODE REVIEW

**Review by deewakar-k — COMMENTED** [review]
can you share the gif or mp4 for sidebar @lixelamos

**Comment by sajdakabir** [comment]
hey @lixelamos , please provide a proper name for your PR and include at least one line explaining it.

**Comment by sajdakabir** [comment]
https://github.com/user-attachments/assets/9fc7272a-5b25-42c9-a8d9-f5a5a76b43e9

it should expend its height not the width


can can take some inspiration from here (https://animation-svelte.vercel.app/magic/dock)

**Comment by lixelamos** [comment]
Thanks for the resource sajda
regards

**Pull request closed without merging**
