### PR TITLE
fix onboarding ui

### LINKED ISSUE #245: polish on boarding ui
- [ ]  cal, stack page requires scrolling to to continue. 
- [ ] over all ui/frame alignments
- [ ] cal, stack pages looks zoomed.

### PR DESCRIPTION
**Pull request by joaorceschini**
fixed onboarding ui
- padronizing icons
- padronizing spaces 
- polish ui in general 
- fixed footer link on stack page

### CODE REVIEW

**Comment by immadsahin** [comment]
Screenshot 2024-10-11 at 11 13 58 AM
[] the gap between contents reduced significantly, there should be more gap, and the google icon is not fixed.
Screenshot 2024-10-11 at 11 16 53 AM
Screenshot 2024-10-11 at 11 17 45 AM

same issue with google auth page,

**Review by immadsahin — CHANGES_REQUESTED** [review]
[] fix google icon
[] more gap between content sections in login, google auth
[] stack page continue i'll do this later looks one into another

**Comment by sajdakabir** [comment]
@oliursahin , What is the status of this pull request?

**Comment by oliursahin** [comment]
> @oliursahin , What is the status of this pull request?

reviewing rn @sajdakabir

**Review by immadsahin — APPROVED** [review]
ui clear for merge @sajdakabir

**Review by sajdakabir — APPROVED** [review]

**Pull request merged**
