### PR TITLE
Feedback changes

### LINKED ISSUE #287: Improve in app feedback
- [ ] Change from linear triage email to sahin@march.cat, add user email to cc and reply to address: sahin@march.cat
- [ ] \[ui\] add hover effect to twitter username, submit button, attach files

- [ ]  check loops smtp if it's working.

### PR DESCRIPTION
**Pull request by madhav-relish**
- Pre-filling user email when feedback form opens
- Users email is used as CC while sending mail
- Added hover effect for x icon
- Added error handling for email

**Checklist**

- [x] Change from linear triage email to sahin@march.cat, add user email to cc and reply to address: sahin@march.cat
(This can be done from the env variable while setting up the project)
- [x] \[ui\] add hover effect to twitter username, submit button, attach files

Fixes: #287 

## Release Notes

- **New Features**
	- Enhanced feedback submission with an email field and improved error handling.
	- User email pre-fills in the feedback form for a streamlined experience.
	- Centralized user data management in the sidebar component.

- **Bug Fixes**
	- Improved error handling for feedback submissions, including server response messages.

- **Style**
	- Adjusted toast notification layout and styling for better visibility and responsiveness.

- **Refactor**
	- Updated user info hook to return user data in a structured format.
	- Clarified user data retrieval in various components by destructuring the user object.

### CODE REVIEW

**Comment by immadsahin** [comment]
Screenshot 2024-10-17 at 12 08 05 PM

- [ ] the feedback input does not go away after submission.
- [ ] toast message uses a outlier color and shows on top right, it should show bottom right ( if we are using a toast)
Screenshot 2024-10-17 at 12 18 01 PM

- [ ] the linear triage addess is still there.

in email name use : march 
subject : feedback sent to march ( no need to give feedback name on subject)

use a no reply address instead of sajda@march.cat ( if 1000 email sent from your address, your normal email will land in spam) — I will create an alias email for from address if we are using google)

- [ ] hide the input email field. no need to tell user that we are using his email for cc, or edit them ( it's standard that we can use their email to send something when they signed up for march) — the ui looks bad with an email there as the user does know what happens with the feedback form)

**Comment by immadsahin** [comment]
added an alias, use feedback-sender@march.cat with same smtp pass.

@sajdakabir go to your gmail settings and add an email address ( add above addreess) > treat this as an alias ( so this will be working)

**Comment by madhav-relish** [comment]
### Changes Made

- [x] Feedback Modal goes away after submission
- [x] Toast outline changed
- [x] Toast position changed to bottom right
- [x] Email input is no longer visible to the user

**Comment by immadsahin** [comment]
did you change the from/ to email  addresses and subject yet? @madhav-relish

**Comment by madhav-relish** [comment]
> did you change the from/ to email addresses and subject yet? @madhav-relish

Subject Has been changed, the from and to addresses you'll have to change from your end by changing the env variables.
@sajdakabir Can you help him.

P.S: You can modify the subject or body as well.

**Pull request merged**
