### PR TITLE
chore: MAR-313 added redirection link to the notification icon

### LINKED ISSUE #584: feedback: go to link is not provided in github pulls
This pull is added in my march inbox as I was added as a reviewer, but there is no link embedded with the icon or somewhere to go to github directly

### PR DESCRIPTION
**Pull request by tanbirali**
# What did you ship?

Modified the getIcon function to do the following
- Passed the sourceUrl to redirect to the notification source
- Wrapped the link to redirect to the source

**Fixes:**

- [x] #584 (GitHub issue number)
- [x] [MAR-313](https://linear.app/marchhq/issue/MAR-313/feedback-go-to-link-is-not-provided-in-github-pulls) (Linear issue number - should be visible at the bottom of the GitHub issue description)

# Checklist:
- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I pinky swear that my codes gonna work as I have testing every possible scenario. 
- [ ] I ignored Coderabbit suggestion because it does not make any sense.
- [ ] I took Coderabbit suggestion under consideration as some of it makes sense.
- [ ] I have commented my code, particularly in hard-to-understand areas.

# OR:

- [ ] shut up and let me cook.

### CODE REVIEW

**Comment by sajdakabir** [comment]
@tanbirali the link should open in a new tab

**Comment by tanbirali** [comment]
Made the requested changes

**Comment by sajdakabir** [comment]
@tanbirali, this pr has a build error. please fix it. 

to test the build error, run `pnpm build`.
Screenshot 2024-11-18 at 10 28 57 AM


Note: use the Petter format in your code editor; it will likely fix the error.

**Comment by tanbirali** [comment]
Fixed the errors generated while trying to build.

**Review by sajdakabir — APPROVED** [review]

**Pull request merged**
